# Generated by Django 3.0.3 on 2020-03-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restswitch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='data',
        ),
    ]
