# Generated by Django 3.0.3 on 2020-03-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restswitch', '0002_remove_switch_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
