# Generated by Django 3.0.3 on 2020-03-04 15:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restswitch', '0003_auto_20200304_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
