# Generated by Django 3.0.3 on 2020-03-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('restswitch', '0004_switch_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.user'),
        ),
    ]
