# Generated by Django 3.0.3 on 2020-03-24 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
