# Generated by Django 3.0.3 on 2020-03-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200325_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
